[phases.setup]
# Nixpacks auto-detects Node.js from package.json

[build]
cmds = ["pnpm run build:node"]

[start]
cmd = "pnpm exec remix-serve build/server/index.js"

[cache]
paths = [
  "/root/.pnpm-store",
  "node_modules",
  ".next",
  "build"

]